require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gym_plans", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GymPlan. As you add validations to GymPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GymPlan.create! valid_attributes
      get gym_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gym_plan = GymPlan.create! valid_attributes
      get gym_plan_url(gym_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_gym_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      gym_plan = GymPlan.create! valid_attributes
      get edit_gym_plan_url(gym_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GymPlan" do
        expect {
          post gym_plans_url, params: { gym_plan: valid_attributes }
        }.to change(GymPlan, :count).by(1)
      end

      it "redirects to the created gym_plan" do
        post gym_plans_url, params: { gym_plan: valid_attributes }
        expect(response).to redirect_to(gym_plan_url(GymPlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GymPlan" do
        expect {
          post gym_plans_url, params: { gym_plan: invalid_attributes }
        }.to change(GymPlan, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post gym_plans_url, params: { gym_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gym_plan" do
        gym_plan = GymPlan.create! valid_attributes
        patch gym_plan_url(gym_plan), params: { gym_plan: new_attributes }
        gym_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the gym_plan" do
        gym_plan = GymPlan.create! valid_attributes
        patch gym_plan_url(gym_plan), params: { gym_plan: new_attributes }
        gym_plan.reload
        expect(response).to redirect_to(gym_plan_url(gym_plan))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        gym_plan = GymPlan.create! valid_attributes
        patch gym_plan_url(gym_plan), params: { gym_plan: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gym_plan" do
      gym_plan = GymPlan.create! valid_attributes
      expect {
        delete gym_plan_url(gym_plan)
      }.to change(GymPlan, :count).by(-1)
    end

    it "redirects to the gym_plans list" do
      gym_plan = GymPlan.create! valid_attributes
      delete gym_plan_url(gym_plan)
      expect(response).to redirect_to(gym_plans_url)
    end
  end
end
