require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/gyms", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Gym. As you add validations to Gym, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Gym.create! valid_attributes
      get gyms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      gym = Gym.create! valid_attributes
      get gym_url(gym)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_gym_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      gym = Gym.create! valid_attributes
      get edit_gym_url(gym)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Gym" do
        expect {
          post gyms_url, params: { gym: valid_attributes }
        }.to change(Gym, :count).by(1)
      end

      it "redirects to the created gym" do
        post gyms_url, params: { gym: valid_attributes }
        expect(response).to redirect_to(gym_url(Gym.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Gym" do
        expect {
          post gyms_url, params: { gym: invalid_attributes }
        }.to change(Gym, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post gyms_url, params: { gym: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested gym" do
        gym = Gym.create! valid_attributes
        patch gym_url(gym), params: { gym: new_attributes }
        gym.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the gym" do
        gym = Gym.create! valid_attributes
        patch gym_url(gym), params: { gym: new_attributes }
        gym.reload
        expect(response).to redirect_to(gym_url(gym))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        gym = Gym.create! valid_attributes
        patch gym_url(gym), params: { gym: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested gym" do
      gym = Gym.create! valid_attributes
      expect {
        delete gym_url(gym)
      }.to change(Gym, :count).by(-1)
    end

    it "redirects to the gyms list" do
      gym = Gym.create! valid_attributes
      delete gym_url(gym)
      expect(response).to redirect_to(gyms_url)
    end
  end
end
