require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/measures", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Measure. As you add validations to Measure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Measure.create! valid_attributes
      get measures_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      measure = Measure.create! valid_attributes
      get measure_url(measure)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_measure_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      measure = Measure.create! valid_attributes
      get edit_measure_url(measure)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Measure" do
        expect {
          post measures_url, params: { measure: valid_attributes }
        }.to change(Measure, :count).by(1)
      end

      it "redirects to the created measure" do
        post measures_url, params: { measure: valid_attributes }
        expect(response).to redirect_to(measure_url(Measure.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Measure" do
        expect {
          post measures_url, params: { measure: invalid_attributes }
        }.to change(Measure, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post measures_url, params: { measure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested measure" do
        measure = Measure.create! valid_attributes
        patch measure_url(measure), params: { measure: new_attributes }
        measure.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the measure" do
        measure = Measure.create! valid_attributes
        patch measure_url(measure), params: { measure: new_attributes }
        measure.reload
        expect(response).to redirect_to(measure_url(measure))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        measure = Measure.create! valid_attributes
        patch measure_url(measure), params: { measure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested measure" do
      measure = Measure.create! valid_attributes
      expect {
        delete measure_url(measure)
      }.to change(Measure, :count).by(-1)
    end

    it "redirects to the measures list" do
      measure = Measure.create! valid_attributes
      delete measure_url(measure)
      expect(response).to redirect_to(measures_url)
    end
  end
end
