require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/neighbors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Neighbor. As you add validations to Neighbor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Neighbor.create! valid_attributes
      get neighbors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      neighbor = Neighbor.create! valid_attributes
      get neighbor_url(neighbor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_neighbor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      neighbor = Neighbor.create! valid_attributes
      get edit_neighbor_url(neighbor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Neighbor" do
        expect {
          post neighbors_url, params: { neighbor: valid_attributes }
        }.to change(Neighbor, :count).by(1)
      end

      it "redirects to the created neighbor" do
        post neighbors_url, params: { neighbor: valid_attributes }
        expect(response).to redirect_to(neighbor_url(Neighbor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Neighbor" do
        expect {
          post neighbors_url, params: { neighbor: invalid_attributes }
        }.to change(Neighbor, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post neighbors_url, params: { neighbor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested neighbor" do
        neighbor = Neighbor.create! valid_attributes
        patch neighbor_url(neighbor), params: { neighbor: new_attributes }
        neighbor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the neighbor" do
        neighbor = Neighbor.create! valid_attributes
        patch neighbor_url(neighbor), params: { neighbor: new_attributes }
        neighbor.reload
        expect(response).to redirect_to(neighbor_url(neighbor))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        neighbor = Neighbor.create! valid_attributes
        patch neighbor_url(neighbor), params: { neighbor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested neighbor" do
      neighbor = Neighbor.create! valid_attributes
      expect {
        delete neighbor_url(neighbor)
      }.to change(Neighbor, :count).by(-1)
    end

    it "redirects to the neighbors list" do
      neighbor = Neighbor.create! valid_attributes
      delete neighbor_url(neighbor)
      expect(response).to redirect_to(neighbors_url)
    end
  end
end
